---
- name: check iptables version
  shell: iptables --version
  register: iptables_version
  changed_when: false

- block:
    - alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy

    - alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy

    - reboot:
        msg: "Reboot initiated by Ansible for iptables-legacy"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
  when: '"nf_tables" in iptables_version.stdout'
